class MusicLists{
    constructor(lists, list){
        this.lists = lists;
        this.list = list;
    }
}

let music_lists = new MusicLists([
    {category: "newest",
    name: "KÖFN",
    songs: [new Music("Al Aramızdan","KÖFN","28.jpg","28.mp3")],
    img: "1.jpg",
    index: 0,
    },
    {category: "newest",
    name: "Türkçe HIT",
    songs: [new Music("Al Aramızdan","KÖFN","28.jpg","28.mp3")],
    img: "24.jpg",
    index: 1,
    },
    {category: "newest",
    name: "Türkçe Slow",
    songs: [new Music("Al Aramızdan","KÖFN","28.jpg","28.mp3")],
    img: "23.jpg",
    index: 2,
    },
    {category: "try",
    name: "Zeynep Bastık",
    songs: [new Music("Ara","Zeynep Bastık","4.jpg","4.mp3")],
    img: "2.jpg",
    index: 3,
    },
    {category: "try",
    name: "Türkçe Dinle",
    songs: [new Music("Masal Gibi","Semicenk","1.jpg","1.mp3"),
            new Music("Küçücüğüm","Yalın","2.jpg","2.mp3"),
            new Music("Anlatamam","Toygar Işıklı","3.jpg","3.mp3"),
            new Music("Ara","Zeynep Bastık","4.jpg","4.mp3"),
            new Music("Arasan Da","UZI","5.jpg","5.mp3"),
            new Music("Makine","UZI","6.jpg","6.mp3"),
            new Music("Bırak Sende Kaybolayım","Toygar Işıklı","7.jpg","7.mp3")],
    img: "3.jpg",
    index: 4,
    },
    {category: "try",
    name: "Gitar Temalı",
    songs: [new Music("Masal Gibi","Semicenk","1.jpg","1.mp3"),
            new Music("Küçücüğüm","Yalın","2.jpg","2.mp3"),
            new Music("Anlatamam","Toygar Işıklı","3.jpg","3.mp3"),
            new Music("Ara","Zeynep Bastık","4.jpg","4.mp3"),
            new Music("Arasan Da","UZI","5.jpg","5.mp3"),
            new Music("Makine","UZI","6.jpg","6.mp3"),
            new Music("Bırak Sende Kaybolayım","Toygar Işıklı","7.jpg","7.mp3")],
    img: "27.jpg",
    index: 5,
    },
    {category: "try",
    name: "Türkçe RAP Custom",
    songs: [new Music("Masal Gibi","Semicenk","1.jpg","1.mp3"),
            new Music("Küçücüğüm","Yalın","2.jpg","2.mp3"),
            new Music("Anlatamam","Toygar Işıklı","3.jpg","3.mp3"),
            new Music("Ara","Zeynep Bastık","4.jpg","4.mp3"),
            new Music("Arasan Da","UZI","5.jpg","5.mp3"),
            new Music("Makine","UZI","6.jpg","6.mp3"),
            new Music("Bırak Sende Kaybolayım","Toygar Işıklı","7.jpg","7.mp3")],
    img: "28.jpg",
    index: 6,
    },
    {category: "try",
    name: "Türkçe Pop",
    songs: [new Music("Masal Gibi","Semicenk","1.jpg","1.mp3"),
            new Music("Küçücüğüm","Yalın","2.jpg","2.mp3"),
            new Music("Anlatamam","Toygar Işıklı","3.jpg","3.mp3"),
            new Music("Ara","Zeynep Bastık","4.jpg","4.mp3"),
            new Music("Arasan Da","UZI","5.jpg","5.mp3"),
            new Music("Makine","UZI","6.jpg","6.mp3"),
            new Music("Bırak Sende Kaybolayım","Toygar Işıklı","7.jpg","7.mp3")],
    img: "29.jpg",
    index: 7,
    },
    {category: "try",
    name: "Hareketli Türkçe",
    songs: [new Music("Masal Gibi","Semicenk","1.jpg","1.mp3"),
            new Music("Küçücüğüm","Yalın","2.jpg","2.mp3"),
            new Music("Anlatamam","Toygar Işıklı","3.jpg","3.mp3"),
            new Music("Ara","Zeynep Bastık","4.jpg","4.mp3"),
            new Music("Arasan Da","UZI","5.jpg","5.mp3"),
            new Music("Makine","UZI","6.jpg","6.mp3"),
            new Music("Bırak Sende Kaybolayım","Toygar Işıklı","7.jpg","7.mp3")],
    img: "30.jpg",
    index: 8,
    },
    {category: "try",
    name: "Yabancı Favoriler",
    songs: [new Music("Masal Gibi","Semicenk","1.jpg","1.mp3"),
            new Music("Küçücüğüm","Yalın","2.jpg","2.mp3"),
            new Music("Anlatamam","Toygar Işıklı","3.jpg","3.mp3"),
            new Music("Ara","Zeynep Bastık","4.jpg","4.mp3"),
            new Music("Arasan Da","UZI","5.jpg","5.mp3"),
            new Music("Makine","UZI","6.jpg","6.mp3"),
            new Music("Bırak Sende Kaybolayım","Toygar Işıklı","7.jpg","7.mp3")],
    img: "31.jpg",
    index: 9,
    },
    {category: "last",
    name: "Türkçe Rock",
    songs: [new Music("Feryat","Hadise","29.jpg","29.mp3"),
            new Music("Aferin","Mabel Matiz","30.jpg","30.mp3"),
            new Music("Herhalde","Tan Taşçı","31.jpg","31.mp3")],
    img: "4.jpg",
    index: 10,
    },
    {category: "last",
    name: "Türkçe Alternatif",
    songs: [new Music("Feryat","Hadise","29.jpg","29.mp3"),
            new Music("Aferin","Mabel Matiz","30.jpg","30.mp3"),
            new Music("Herhalde","Tan Taşçı","31.jpg","31.mp3")],
    img: "8.jpg",
    index: 11,
    },
    {category: "last",
    name: "Türkçe Alternatif",
    songs: [new Music("Feryat","Hadise","29.jpg","29.mp3"),
            new Music("Aferin","Mabel Matiz","30.jpg","30.mp3"),
            new Music("Herhalde","Tan Taşçı","31.jpg","31.mp3")],
    img: "9.jpg",
    index: 12,
    },
    {category: "last",
    name: "Türkçe Hafif Müzik",
    songs: [new Music("Feryat","Hadise","29.jpg","29.mp3"),
            new Music("Aferin","Mabel Matiz","30.jpg","30.mp3"),
            new Music("Herhalde","Tan Taşçı","31.jpg","31.mp3")],
    img: "10.jpg",
    index: 13,
    },
    {category: "last",
    name: "En Güzel Türküler",
    songs: [new Music("Feryat","Hadise","29.jpg","29.mp3"),
            new Music("Aferin","Mabel Matiz","30.jpg","30.mp3"),
            new Music("Herhalde","Tan Taşçı","31.jpg","31.mp3")],
    img: "11.jpg",
    index: 14,
    },
    {category: "last",
    name: "En Güzel Türküler",
    songs: [new Music("Feryat","Hadise","29.jpg","29.mp3"),
            new Music("Aferin","Mabel Matiz","30.jpg","30.mp3"),
            new Music("Herhalde","Tan Taşçı","31.jpg","31.mp3")],
    img: "12.jpg",
    index: 15,
    },
    {category: "last",
    name: "Türkçe Pop",
    songs: [new Music("Feryat","Hadise","29.jpg","29.mp3"),
            new Music("Aferin","Mabel Matiz","30.jpg","30.mp3"),
            new Music("Herhalde","Tan Taşçı","31.jpg","31.mp3")],
    img: "13.jpg",
    index: 16,
    },
    {category: "last",
    name: "Türkçe Mutlu Şarkılar",
    songs: [new Music("Feryat","Hadise","29.jpg","29.mp3"),
            new Music("Aferin","Mabel Matiz","30.jpg","30.mp3"),
            new Music("Herhalde","Tan Taşçı","31.jpg","31.mp3")],
    img: "14.jpg",
    index: 17,
    },
    {category: "most",
    name: "Türkçe 90'lar",
    songs: [new Music("Kül","Cem Adrian","25.jpg","25.mp3"),
            new Music("Sonsuza Dek","Tuğba Yurt","26.jpg","26.mp3"),
            new Music("Nefes","Derya Uluğ","27.jpg","27.mp3")],
    img: "15.jpg",
    index: 18,
    },
    {category: "most",
    name: "Türkçe Slow",
    songs: [new Music("Kül","Cem Adrian","25.jpg","25.mp3"),
            new Music("Sonsuza Dek","Tuğba Yurt","26.jpg","26.mp3"),
            new Music("Nefes","Derya Uluğ","27.jpg","27.mp3")],
    img: "5.jpg",
    index: 19,
    },
    {category: "most",
    name: "Türkçe 2000'ler",
    songs: [new Music("Kül","Cem Adrian","25.jpg","25.mp3"),
            new Music("Sonsuza Dek","Tuğba Yurt","26.jpg","26.mp3"),
            new Music("Nefes","Derya Uluğ","27.jpg","27.mp3")],
    img: "16.jpg",
    index: 20,
    },
    {category: "most",
    name: "Türkçe Remix",
    songs: [new Music("Kül","Cem Adrian","25.jpg","25.mp3"),
            new Music("Sonsuza Dek","Tuğba Yurt","26.jpg","26.mp3"),
            new Music("Nefes","Derya Uluğ","27.jpg","27.mp3")],
    img: "17.jpg",
    index: 21,
    },
    {category: "most",
    name: "Türkçe Top 100",
    songs: [new Music("Kül","Cem Adrian","25.jpg","25.mp3"),
            new Music("Sonsuza Dek","Tuğba Yurt","26.jpg","26.mp3"),
            new Music("Nefes","Derya Uluğ","27.jpg","27.mp3")],
    img: "18.jpg",
    index: 22,
    },
    {category: "most",
    name: "Türkçe Hiphop",
    songs: [new Music("Kül","Cem Adrian","25.jpg","25.mp3"),
            new Music("Sonsuza Dek","Tuğba Yurt","26.jpg","26.mp3"),
            new Music("Nefes","Derya Uluğ","27.jpg","27.mp3")],
    img: "19.jpg",
    index: 23,
    },
    {category: "nostalji",
    name: "Türkçe Old School Rap",
    songs: [new Music("Bilmem Mi?","Sefo","22.jpg","22.mp3")],
    img: "6.jpg",
    index: 24,
    },
    {category: "bread",
    name: "Türkçe Pop",
    songs: [new Music("Tanrım Reva Mı","Semicenk","11.jpg","11.mp3"),
            new Music("Geri Dönemedim","Semicenk","12.jpg","12.mp3"),
            new Music("Pişman Değilim","Semicenk","13.jpg","13.mp3")],
    img: "7.jpg",
    index: 25,
    }
], music_list);
